#!/bin/bash

# Create directory
mkdir -p desktop/gnome

echo "Backing up GNOME settings..."




# 1. Dump Shell settings (Extensions, Layouts)
# Filter out: Location data, Command history, Usage stats, etc.
echo "# generated by 'dconf dump /org/gnome/shell/'" > desktop/gnome/new-dconf-shell.ini
dconf dump /org/gnome/shell/ | sed \
    -e '/^\[weather/,/^$/d' \
    -e '/^\[world-clocks/,/^$/d' \
    -e '/command-history=/d' \
    -e '/launcher-stats=/d' \
    -e '/history=/d' \
    -e '/input-mode-list=/d' \
    >> desktop/gnome/new-dconf-shell.ini

# 2. Dump Desktop settings (Interface, Peripherals)
# Usually cleaner, but good to be safe
echo "# generated by 'dconf dump /org/gnome/desktop/'" > desktop/gnome/new-dconf-desktop.ini
dconf dump /org/gnome/desktop/ | sed \
    -e '/history=/d' \
    >> desktop/gnome/new-dconf-desktop.ini


echo "Done. Sensitive data filtered."

# check and then git add/commit/push if everthing is ok
