[battery]
full_symbol = "* "
charging_symbol = "^ "
discharging_symbol = "v "
unknown_symbol = "? "
empty_symbol = "! "

[character]
success_symbol = '[#>](bold green)'
error_symbol = '[#>](bold red)'

[erlang]
symbol = "e "

[nodejs]
symbol = "[#](bold green) "

[pulumi]
symbol = "[P] "

[typst]
symbol = "t "
