# === General ===
set -g mouse on                # enable mouse support
setw -g mode-keys vi           # use vi key bindings in copy mode
set -g history-limit 10000     # optional: keep more scrollback history
set -a terminal-features "tmux-256color:RGB"
set -g extended-keys on
set -g base-index 1
set -g renumber-windows on
set -g status-interval 5

bind r source-file "~/.tmux.conf"

# also copy to system clipboard 
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "wl-copy"  # Wayland

